### ISSUE TITLE
[v2] Loading overlay and icon spinner that spins

### ISSUE THREAD

**Issue by df-git** [ec-europa/europa-component-library#1321]
Dear ECL team,
- Is there a full page loading overlay (like the grey ones)?
- In the icon list I can see an icons called "spinner" which is actually not spinning. Do we have to add some class or script to make it spin (like the fa-spin in font awesome)?

Thank you in advance

**Comment by yhuard** [comment]
Hi @df-git

- there's no full page loading overlay; IMHO if your plan is to use an full page overlay and only display a spinner on top of it, it will hurt the user experience. Please contact COMM Europa Management and ask for UX support, they might suggest you a better approach :) If this is not what you had in mind, can you please describe your goal?
- currently, there's (almost) no animation in the library (except for arrow up/down icons). If you want to add a spinner effect, here are a few lines that will help you:

```css
.custom-spinner {
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
```

now you can add `.custom-spinner` to your icon to make it spin
