### ISSUE TITLE
ecl-ec-preset-website.css does not contain all css needed to start a new website

### ISSUE THREAD

**Issue by dhamaris** [ec-europa/europa-component-library#719]
Hi, I have been doing the revamping of a website and have needed some css from other files in order to make my site look like the demo, this is the css I have needed to add.

```

/** generic-component-link.scss, see https://ec-europa.github.io/europa-component-library/node_modules/@ecl/generic-component-link/generic-component-link.scss */
.ecl-link--external::after {
    display: inline-block;
    font-family: 'EuropaIcons';
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-style: normal;
    font-variant: normal;
    font-weight: normal;
    line-height: 1;
    margin-left: 4px;
    speak: none;
    text-decoration: none;
    text-transform: none;
    content: '\e825';
    font-size: 75%;
    margin-left: 0.4em;
    margin-right: 0.2em;
}

@media (min-width: 768px){
.ecl-table thead tr:first-child th {
    border-bottom: 1px solid #CECECE;
}
}

/** Added from ecl-ec-preset-website.scss, it was not present in ecl-ec-preset-website.css **/
.ecl-button--caret-right:after {
    content: "\e828";
}
.ecl-button--caret-right:after, .ecl-button--caret-up:after {
    display: inline-block;
    font-family: EuropaIcons;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-style: normal;
    font-variant: normal;
    font-weight: 400;
    line-height: 1;
    margin-left: 4px;
    speak: none;
    text-decoration: none;
    text-transform: none;
    font-size: .875rem;
    margin-left: .66rem;
}

/** Added from ecl-ec-preset-website.scss, it was not present in ecl-ec-preset-website.css **/
.ecl-breadcrumb__segment--last span{
	font-weight:700;
}

.ecl-breadcrumb__segment--last {
    color: #bfd0e4;
}

```

Can you please explain me if I am missing something? I am currently using the 1.0.0 release.

**Comment by yhuard** [comment]
Thank you @dhamaris for reporting this, I will investigate and come back to you soon

**Comment by yhuard** [comment]
I've checked the published CSS of v1.0.0. Here's what I've found:

- `ecl-link--external::after` doesn't exist but `ecl-link--external:after` does. No need to redeclare it.

- about `@media (min-width: 768px) .ecl-table thead tr:first-child th`

in the published css, the definition is:

```css
@media (min-width:768px) {
  .ecl-table thead tr:first-child th {
    border-bottom: 1px solid #404040;
    vertical-align: top
  }
}
```

the border-bottom color is different from your definition. Where does your color come from? In our styleguide, its's `#404040`, just as in our published CSS.

- already there:

```css
.ecl-button--caret-right:after {
    content: "\e828";
}

.ecl-button--caret-right:after, .ecl-button--caret-up:after {
    display: inline-block;
    font-family: EuropaIcons;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    font-style: normal;
    font-variant: normal;
    font-weight: 400;
    line-height: 1;
    margin-left: 4px;
    speak: none;
    text-decoration: none;
    text-transform: none;
    font-size: .875rem;
    margin-left: .66rem;
}
```

nothing to do

- `.ecl-breadcrumb__segment--last`: new feature added in https://github.com/ec-europa/europa-component-library/pull/701/files#diff-5a0cabcb07611e09d286659866c74496R48 it will be published in ECL v1.2.0
